#Configuración para el entorno de desarollo(DEV)
server.port=8080

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/CONTDIR?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

#Mostrar consultas SQL en consola.
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect